<a href="https://colab.research.google.com/github/PatrickRuan/NLP_100/blob/main/homework/Day019_K_fold%E4%BD%9C%E6%A5%AD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 作業目標：運用scikit-learn API 實現K-fold分割資料

---

In [35]:
from google.colab import drive
drive.mount('/content/drive/')

path = 'drive/My Drive/學習/Cupoy/NLP_Cupoy_Pre/d019/'

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).


### 讀入資料

In [36]:
import pandas as pd
dataset = pd.read_csv(path+r'Social_Network_Ads.csv')

In [37]:
dataset

User ID  Gender   Age  EstimatedSalary  Purchased
0    15624510    Male  19.0          19000.0          0
1    15810944    Male  35.0          20000.0          0
2    15668575  Female  26.0          43000.0          0
3    15603246  Female  27.0          57000.0          0
4    15804002    Male  19.0          76000.0          0
..        ...     ...   ...              ...        ...
395  15691863  Female  46.0          41000.0          1
396  15706071    Male  51.0          23000.0          1
397  15654296  Female  50.0          20000.0          1
398  15755018    Male  36.0          33000.0          0
399  15594041  Female  49.0          36000.0          1

[400 rows x 5 columns]

### 取出訓練特徵與標註

In [38]:
X = dataset[['User ID', 'Gender', 'Age', 'EstimatedSalary']].values
Y = dataset['Purchased'].values

---

In [39]:
import numpy as np
from sklearn.model_selection import KFold

### 將訓練資料按照順序切割成10等分

In [40]:

kf = KFold(n_splits= 10, random_state= 43, shuffle=False)
kf.get_n_splits(X)

print(kf)


KFold(n_splits=10, random_state=43, shuffle=False)


/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_split.py:296: FutureWarning: Setting a random_state has no effect since shuffle is False. This will raise an error in 0.24. You should leave random_state to its default (None), or set shuffle=True.
  FutureWarning


### 將訓練資料隨機切割成10等分

In [41]:
kf = KFold(n_splits= 10, random_state= 43, shuffle=True)
kf.get_n_splits(X)

print(kf)

KFold(n_splits=10, random_state=43, shuffle=True)


---

### 取出 切割資料對應位置

In [42]:
train_split = kf.split(X)
next(train_split)

(array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  13,
         14,  15,  16,  17,  18,  19,  21,  22,  23,  24,  25,  26,  28,
         29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,
         42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,
         56,  57,  58,  60,  61,  63,  65,  66,  68,  69,  70,  71,  72,
         73,  74,  75,  76,  77,  78,  79,  80,  81,  83,  84,  85,  86,
         87,  88,  89,  90,  91,  92,  93,  95,  96,  97,  98,  99, 100,
        101, 102, 104, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115,
        116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128,
        129, 130, 131, 132, 133, 134, 135, 137, 140, 141, 142, 144, 145,
        146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158,
        159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171,
        172, 173, 174, 175, 176, 177, 178, 180, 181, 182, 183, 184, 186,
        187, 188, 189, 190, 191, 192, 193, 194, 195

### Or

In [43]:
for train_index, test_index in kf.split(X):
    print("TRAIN:", train_index, "TEST:", test_index)

TRAIN: [  0   1   2   3   4   5   6   7   8   9  10  11  13  14  15  16  17  18
  19  21  22  23  24  25  26  28  29  30  31  32  33  34  35  36  37  38
  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  56  57
  58  60  61  63  65  66  68  69  70  71  72  73  74  75  76  77  78  79
  80  81  83  84  85  86  87  88  89  90  91  92  93  95  96  97  98  99
 100 101 102 104 106 107 108 109 110 111 112 113 114 115 116 117 118 119
 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 137 140
 141 142 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159
 160 161 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177
 178 180 181 182 183 184 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 224 225 226 227 231 232 235 236 237 238 239
 240 241 242 244 245 246 247 248 249 250 251 252 253 254 255 256 257 258
 259 260 261 262 263 264 265 266 267 268 269

### 取出切割資料：trainset / testset 特徵(x_train/x_test)/標註(y_train/y_test)

In [66]:
for train_index, test_index in kf.split(X):
  print(train_index, test_index)
  X_train, X_test = X[train_index], X[test_index]
  y_train, y_test = Y[train_index], Y[test_index]

[  0   1   2   3   4   5   6   7   8   9  10  11  13  14  15  16  17  18
  19  21  22  23  24  25  26  28  29  30  31  32  33  34  35  36  37  38
  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  56  57
  58  60  61  63  65  66  68  69  70  71  72  73  74  75  76  77  78  79
  80  81  83  84  85  86  87  88  89  90  91  92  93  95  96  97  98  99
 100 101 102 104 106 107 108 109 110 111 112 113 114 115 116 117 118 119
 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 137 140
 141 142 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159
 160 161 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177
 178 180 181 182 183 184 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 224 225 226 227 231 232 235 236 237 238 239
 240 241 242 244 245 246 247 248 249 250 251 252 253 254 255 256 257 258
 259 260 261 262 263 264 265 266 267 268 269 270 27

In [71]:
X_train[13:18]

array([[15704987, 'Male', 32.0, 18000.0],
       [15628972, 'Male', 18.0, 82000.0],
       [15697686, 'Male', 29.0, 80000.0],
       [15617482, 'Male', 45.0, 26000.0],
       [15704583, 'Male', 46.0, 28000.0]], dtype=object)

In [73]:
X[13:18]

array([[15704987, 'Male', 32.0, 18000.0],
       [15628972, 'Male', 18.0, 82000.0],
       [15697686, 'Male', 29.0, 80000.0],
       [15733883, 'Male', 47.0, 25000.0],
       [15617482, 'Male', 45.0, 26000.0]], dtype=object)